name: CI
on: 
  push:
  pull_request:
    branches:
      - master
jobs:
  ci:
    name: run dawn CI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm install
    - run: npm test
