name: Continuous-Integration
on:
  push:
    branches:
      - chore/actions
jobs:
  install:
    name: run npm install
    runs-on: ubuntu-latest
    steps:
      - name: install
        run: |
          npm install
      - name: test
        run: |
          npm run dntest
