name: Continuous-Integration
on:
  push:
    branches:
      - chore/actions
jobs:
  ci:
    name: run dawn CI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm test
