name: Continuous-Integration
on:
  push:
    branches:
      - chore/actions
jobs:
  ci:
    name: run dawn CI
    runs-on: ubuntu-latest
    steps:
      - name: install
        run: |
          npm install
      - name: test
        run: |
          npm run dntest
