name: Continuous-Integration
on:
  push:
    branches:
      - chore/actions
jobs:
  install:
    name: run npm install
    runs-on: ubuntu-latest
    steps:
      - name: install
      - uses: actions/checkout@v2
      - run: |
          npm install
